import { useState } from "react";
import { Bell, Eye, Globe2, Keyboard, RotateCcw, Save, ShieldCheck, Volume2 } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";

const settings = [
  { id: "notifications", icon: Bell, title: "Learning reminders", description: "Receive gentle reminders to continue your learning path." },
  { id: "captions", icon: Eye, title: "Always show captions", description: "Keep supporting text visible during translation and lessons." },
  { id: "sound", icon: Volume2, title: "Sound feedback", description: "Play subtle confirmation sounds for supported interactions." },
];
export default function Settings() {
  const [values, setValues] = useState({ notifications: true, captions: true, sound: false });
  const [notice, setNotice] = useState(""); const defaults = { notifications: true, captions: true, sound: false };
  return <DashboardLayout title="Settings" activeItem="settings"><div className="mx-auto max-w-4xl space-y-6"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-tight text-slate-900">Your preferences</h2><p className="mt-1 text-sm text-slate-500">Set up SIGNIX to support the way you communicate and learn.</p></div><div className="flex gap-2"><button type="button" onClick={() => { setValues(defaults); setNotice("Preferences reset to their defaults."); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600"><RotateCcw className="h-4 w-4" />Reset</button><button type="button" onClick={() => setNotice("Preferences saved locally and ready for backend persistence.")} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-sm font-medium text-white"><Save className="h-4 w-4" />Save</button></div></section>{notice && <p role="status" className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}<SettingsCard title="Accessibility" icon={Keyboard}><div className="rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><strong>Accessibility-first by design.</strong><p className="mt-1 text-blue-700">Keyboard navigation, visible focus states, and adaptable layouts are enabled across the platform.</p></div></SettingsCard><SettingsCard title="Experience" icon={Globe2}>{settings.map((setting) => <Toggle key={setting.id} {...setting} checked={values[setting.id]} onChange={() => setValues((current) => ({ ...current, [setting.id]: !current[setting.id] }))} />)}</SettingsCard><SettingsCard title="Privacy & security" icon={ShieldCheck}><div className="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-800">Translation data</p><p className="mt-1 text-sm text-slate-500">Your local workspace is ready for secure backend storage.</p></div><button type="button" onClick={() => setNotice("Data controls will be available when secure storage is connected.")} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 hover:border-blue-300 hover:text-blue-700">Manage data</button></div></SettingsCard></div></DashboardLayout>;
}
function SettingsCard({ title, icon: Icon, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-5 w-5" /></span><h3 className="text-lg font-semibold text-slate-900">{title}</h3></div><div className="space-y-1">{children}</div></section>; }
function Toggle({ icon: Icon, title, description, checked, onChange }) { return <div className="flex items-center gap-4 rounded-xl p-3 hover:bg-slate-50"><Icon className="h-5 w-5 shrink-0 text-slate-400" /><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-800">{title}</p><p className="mt-0.5 text-sm text-slate-500">{description}</p></div><button type="button" role="switch" aria-checked={checked} onClick={onChange} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? "bg-blue-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /></button></div>; }
