import bcrypt from 'bcrypt'; import crypto from 'crypto'; import jwt from 'jsonwebtoken';
import { Otp, RefreshToken, User, UserSettings } from '../models/index.js'; import { env } from '../config/env.js'; import { AppError, asyncHandler, ok } from '../utils/http.js'; import { hash, issueAccessToken, issueRefreshToken } from '../services/tokenService.js'; import { sendOtp } from '../services/mailService.js';
const publicUser = (user) => ({ id: user.id, fullName: user.fullName, email: user.email, isEmailVerified: user.isEmailVerified, avatarUrl: user.avatarUrl });
const generateOtp = () => String(crypto.randomInt(100000, 1000000));
async function deliverOtp(email, purpose, pendingRegistration) { const existing = await Otp.findOne({ email, purpose }).sort({ createdAt: -1 }); await Otp.deleteMany({ email, purpose }); const code = generateOtp(); await Otp.create({ email, purpose, codeHash: await bcrypt.hash(code, 10), expiresAt: new Date(Date.now() + 600000), pendingRegistration: pendingRegistration ?? existing?.pendingRegistration }); await sendOtp(email, code, purpose); }
async function session(res, user, req) { const accessToken = issueAccessToken(user); const refreshToken = issueRefreshToken(user); await RefreshToken.create({ user: user.id, tokenHash: hash(refreshToken), expiresAt: new Date(Date.now() + 30 * 86400000), userAgent: req.get('user-agent') }); res.cookie('signix_refresh', refreshToken, { httpOnly: true, secure: env.nodeEnv === 'production', sameSite: 'lax', maxAge: 30 * 86400000 }); return { user: publicUser(user), accessToken }; }
export const register = asyncHandler(async (req, res) => { const { fullName, email, password, acceptTerms } = req.body; if (!acceptTerms) throw new AppError('You must accept the Terms to continue.', 422, 'TERMS_REQUIRED'); if (await User.exists({ email })) throw new AppError('An account already exists for this email.', 409, 'EMAIL_EXISTS'); await deliverOtp(email, 'verify-email', { fullName, passwordHash: await bcrypt.hash(password, 12), acceptedTermsAt: new Date() }); ok(res, { email, pendingVerification: true }, 201); });
export const verifyOtp = asyncHandler(async (req, res) => { const { email, code, purpose = 'verify-email' } = req.body; const otp = await Otp.findOne({ email, purpose }).sort({ createdAt: -1 }); if (!otp || otp.expiresAt < new Date() || !(await bcrypt.compare(code, otp.codeHash))) throw new AppError('The verification code is invalid or expired.', 400, 'INVALID_OTP'); if (purpose === 'verify-email') { let user; if (otp.pendingRegistration) { user = await User.create({ ...otp.pendingRegistration, email, isEmailVerified: true }); await UserSettings.create({ user: user.id }); } else { user = await User.findOne({ email }); if (!user) throw new AppError('Registration is no longer available.', 400, 'INVALID_OTP'); user.isEmailVerified = true; await user.save(); } await otp.deleteOne(); return ok(res, await session(res, user, req)); } await otp.deleteOne(); const resetToken = jwt.sign({ email, purpose: 'reset-password' }, env.accessSecret, { expiresIn: '15m' }); ok(res, { resetToken }); });
export const resendOtp = asyncHandler(async (req, res) => { const { email, purpose = 'verify-email' } = req.body; if (purpose === 'verify-email' && !(await Otp.exists({ email, purpose }))) throw new AppError('No pending registration exists for this email.', 404, 'NOT_FOUND'); await deliverOtp(email, purpose); ok(res, { email, sent: true }); });
export const login = asyncHandler(async (req, res) => { const user = await User.findOne({ email: req.body.email }).select('+passwordHash'); if (!user || !(await bcrypt.compare(req.body.password, user.passwordHash))) throw new AppError('Invalid email or password.', 401, 'INVALID_CREDENTIALS'); if (!user.isEmailVerified) { await deliverOtp(user.email, 'verify-email'); throw new AppError('Verify your email before signing in. A new code was sent.', 403, 'EMAIL_UNVERIFIED'); } ok(res, await session(res, user, req)); });
export const forgotPassword = asyncHandler(async (req, res) => { const user = await User.findOne({ email: req.body.email }); if (user) await deliverOtp(user.email, 'reset-password'); ok(res, { sent: true }); });
export const resetPassword = asyncHandler(async (req, res) => { let claims; try { claims = jwt.verify(req.body.resetToken, env.accessSecret); } catch { throw new AppError('The reset session is invalid or expired.', 400, 'INVALID_RESET_TOKEN'); } if (claims.purpose !== 'reset-password') throw new AppError('Invalid reset session.', 400, 'INVALID_RESET_TOKEN'); const user = await User.findOne({ email: claims.email }).select('+passwordHash'); if (!user) throw new AppError('Account not found.', 404, 'NOT_FOUND'); user.passwordHash = await bcrypt.hash(req.body.password, 12); await user.save(); await RefreshToken.deleteMany({ user: user.id }); ok(res, { reset: true }); });
export const refresh = asyncHandler(async (req, res) => { const token = req.cookies.signix_refresh || req.body.refreshToken; if (!token) throw new AppError('Refresh token required.', 401, 'UNAUTHENTICATED'); let claims; try { claims = jwt.verify(token, env.refreshSecret); } catch { throw new AppError('Refresh token invalid.', 401, 'UNAUTHENTICATED'); } const stored = await RefreshToken.findOne({ user: claims.sub, tokenHash: hash(token), revokedAt: null }); if (!stored) throw new AppError('Refresh token revoked.', 401, 'UNAUTHENTICATED'); const user = await User.findById(claims.sub); ok(res, { accessToken: issueAccessToken(user), user: publicUser(user) }); });
export const logout = asyncHandler(async (req, res) => { const token = req.cookies.signix_refresh || req.body.refreshToken; if (token) await RefreshToken.updateOne({ tokenHash: hash(token) }, { revokedAt: new Date() }); res.clearCookie('signix_refresh'); ok(res, { loggedOut: true }); });
